ALTER TYPE "DashboardCommandType" ADD VALUE 'CREATE_PROJECT';
ALTER TYPE "DashboardCommandType" ADD VALUE 'UPDATE_PROJECT_CONFIG';
ALTER TYPE "DashboardCommandType" ADD VALUE 'ACTIVATE_PROJECT';
ALTER TYPE "DashboardCommandType" ADD VALUE 'DEACTIVATE_PROJECT';
